### ISSUE TITLE
Entities.Serializer.Serialize throws an error if parameter is interface

### ISSUE THREAD

**Issue by JakubKorcak** [danielwertheim/mycouch#130]
Hello,

I ran into really weird behaviour when calling Entities.Serializer.Serialize(doc). 
As I am not really able to describe properly, what is going on, I will try to do so in the code below.

Let's assume following structure:

```
public interface ITest { }

public class Test : ITest
{
    public string Foo { get; private set; }

    public Test(string foo)
    {
        Foo = foo;
    }
}

public class DocHandler
{
    public void Bar(ITest test)
    {
        using(var client = new MyCouchClient("http://testUser:testPassword@localhost:5984", "testDb")
        {
            var a = client.Serializer.Serialize(test);   // executes properly
            var b = client.Documents.Serializer.Serialize(test); // executes properly
            var c = client.Entities.Serializer.Serialize(test);  //throws an exception (see below)
        }
    }
}
```

When I run this code (call `public void Bar(ITest test)` function) the last serialization (`client.Entities.Serializer.Serialize(test);`) will throw following Exception:

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at MyCouch.EntitySchemes.EntityIdMember.GetMemberRankingIndex(Type entityType, String membername, Int32 level)
   at MyCouch.EntitySchemes.EntityIdMember.GetMemberRankingIndex(Type entityType, String membername, Int32 level)
   at MyCouch.Serialization.DocumentJsonWriter.WritePropertyName(String name)
   at MyCouch.Serialization.Conventions.SerializationConventionWriter.WriteName(String name)
   at MyCouch.Serialization.Conventions.StringSerializationConvention.WriteIfValueExists(String value, ISerializationConventionWriter writer)
   at MyCouch.Serialization.DocumentJsonWriter.WriteDocumentMeta(DocumentSerializationMeta meta)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteObjectStart(JsonWriter writer, Object value, JsonContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at MyCouch.Serialization.DefaultSerializer.Serialize[T](T item)
```
If you change the signature of the `public void Bar(ITest test)` function to `public void Bar(Test test)` serialization call `var c = client.Entities.Serializer.Serialize(test);` will execute with no issue

**Comment by danielwertheim** [comment]
https://github.com/danielwertheim/mycouch/wiki/documentation#serialization

When using Entities it requires certain members etc. Like Id and Rev.

**Comment by JakubKorcak** [comment]
Once signature of Interface was changed to contain also _rev and _id properties everything seems to be working fine. Closing the issue
